using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using OpenSiconfi.Domain.Entities;

namespace OpenSiconfi.Domain.Seed
{
  public class SeedComplementoFonteRecurso
  {
    public static void Data(ModelBuilder modelBuilder)
    {
      List<ComplementoFonteRecurso> dados = new()
      {
        new ComplementoFonteRecurso() { Id = 1, Exercicio = 2021, Codigo = 1111, Nomenclatura = "Benefícios previdenciários - Poder Executivo – Fundo em Capitalização (Plano Previdenciário)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 2, Exercicio = 2021, Codigo = 1121, Nomenclatura = "Benefícios previdenciários - Poder Legislativo – Fundo em Capitalização (Plano Previdenciário)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 3, Exercicio = 2021, Codigo = 1122, Nomenclatura = "Benefícios previdenciários - Tribunal de Contas – Fundo em Capitalização (Plano Previdenciário)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 4, Exercicio = 2021, Codigo = 1123, Nomenclatura = "Benefícios previdenciários - Tribunal de Contas dos Municípios – Fundo em Capitalização (Plano Previdenciário)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 5, Exercicio = 2021, Codigo = 1124, Nomenclatura = "Benefícios previdenciários - Ministério Público de Contas – Fundo em Capitalização (Plano Previdenciário)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 6, Exercicio = 2021, Codigo = 1125, Nomenclatura = "Benefícios previdenciários - Ministério Público de Contas dos Municípios – Fundo em Capitalização (Plano Previdenciário)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 7, Exercicio = 2021, Codigo = 1131, Nomenclatura = "Benefícios previdenciários - Tribunal de Justiça – Fundo em Capitalização (Plano Previdenciário)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 8, Exercicio = 2021, Codigo = 1132, Nomenclatura = "Benefícios previdenciários - Tribunal de Justiça Militar – Fundo em Capitalização (Plano Previdenciário)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 9, Exercicio = 2021, Codigo = 1141, Nomenclatura = "Benefícios previdenciários - Ministério Público – Fundo em Capitalização (Plano Previdenciário)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 10, Exercicio = 2021, Codigo = 1151, Nomenclatura = "Benefícios previdenciários - Defensoria Pública - Fundo em Capitalização (Plano Previdenciário)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 11, Exercicio = 2021, Codigo = 2111, Nomenclatura = "Benefícios previdenciários - Poder Executivo - Fundo em Repartição (Plano Financeiro)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 12, Exercicio = 2021, Codigo = 2121, Nomenclatura = "Benefícios previdenciários - Poder Legislativo - Fundo em Repartição (Plano Financeiro)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 13, Exercicio = 2021, Codigo = 2122, Nomenclatura = "Benefícios previdenciários - Tribunal de Contas - Fundo em Repartição (Plano Financeiro)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 14, Exercicio = 2021, Codigo = 2123, Nomenclatura = "Benefícios previdenciários - Tribunal de Contas dos Municípios - Fundo em Repartição (Plano Financeiro)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 15, Exercicio = 2021, Codigo = 2124, Nomenclatura = "Benefícios previdenciários - Ministério Público de Contas - Fundo em Repartição (Plano Financeiro)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 16, Exercicio = 2021, Codigo = 2125, Nomenclatura = "Benefícios previdenciários - Ministério Público de Contas dos Municípios - Fundo em Repartição (Plano Financeiro)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 17, Exercicio = 2021, Codigo = 2131, Nomenclatura = "Benefícios previdenciários - Tribunal de Justiça - Fundo em Repartição (Plano Financeiro)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 18, Exercicio = 2021, Codigo = 2132, Nomenclatura = "Benefícios previdenciários - Tribunal de Justiça Militar - Fundo em Repartição (Plano Financeiro)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 19, Exercicio = 2021, Codigo = 2141, Nomenclatura = "Benefícios previdenciários - Ministério Público - Fundo em Repartição (Plano Financeiro)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 20, Exercicio = 2021, Codigo = 2151, Nomenclatura = "Benefícios previdenciários - Defensoria Pública - Fundo em Repartição (Plano Financeiro)", Especificacao = "Identifica a qual Poder ou Órgão se refere a despesa quando ela é executada no PO RPPS, possibilitando a geração automática dos valores das linhas referentes a “Pessoal Inativo e Pensionista” no quadro da “Despesa Bruta com Pessoal” do Demonstratativo da Despesa com Pessoal, bem como a identificação das despesas com benefícios previdenciários efetuados em cada plano quando há segregação das massas." },
        new ComplementoFonteRecurso() { Id = 21, Exercicio = 2021, Codigo = 3110, Nomenclatura = "Transferências da União decorrentes de emedas parlamentares individuais.", Especificacao = "Transferências decorrentes de emedas parlamentares individuais, na forma prevista do parágrafo 9º do art. 166, da CF/88, acrescido pela Emenda Constitucional nº 86/2015" },
        new ComplementoFonteRecurso() { Id = 22, Exercicio = 2021, Codigo = 3120, Nomenclatura = "Transferências da União decorrentes de emedas parlamentares de bancada.", Especificacao = "Transferências decorrentes de emedas parlamentares de bancada, na forma prevista do parágrafo 16 do art. 166, da CF/88, acrescido por Emenda Constitucional a ser publicada, proveniente da PEC nº 34/2019." }
      };

      modelBuilder.Entity<ComplementoFonteRecurso>().HasData(dados);
    }
  }
}