// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenSiconfi.Domain;

namespace OpenSiconfi.Core.Migrations
{
    [DbContext(typeof(OSContext))]
    [Migration("20210601065526_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("OpenSiconfi.Domain.Entities.ComplementoFonteRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("codigo");

                    b.Property<string>("Especificacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("especificacao");

                    b.Property<int>("Exercicio")
                        .HasColumnType("integer")
                        .HasColumnName("exercicio");

                    b.Property<string>("Nomenclatura")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nomenclatura");

                    b.HasKey("Id");

                    b.ToTable("complemento_fonte_recurso");
                });

            modelBuilder.Entity("OpenSiconfi.Domain.Entities.FonteRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CodigoPrincipal")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("codigo_principal");

                    b.Property<string>("Detalhamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detalhamento");

                    b.Property<string>("Especificacao")
                        .HasColumnType("text")
                        .HasColumnName("especificacao");

                    b.Property<int>("Exercicio")
                        .HasColumnType("integer")
                        .HasColumnName("exercicio");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("fonte_recurso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoPrincipal = "001",
                            Detalhamento = "0000",
                            Especificacao = "Recursos da entidade de livre aplicação",
                            Exercicio = 2021,
                            Nome = "Recursos Ordinários"
                        },
                        new
                        {
                            Id = 2,
                            CodigoPrincipal = "090",
                            Detalhamento = "0000",
                            Especificacao = "Outros recursos não vinculados que não se enquadrem nas especificações acima",
                            Exercicio = 2021,
                            Nome = "Outros Recursos Não Vinculados"
                        },
                        new
                        {
                            Id = 3,
                            CodigoPrincipal = "111",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que vinculam os recursos de impostos à educação no momento da arrecadação da receita. Nas situações em que os entes não efetuam a vinculação do recurso na origem, a aplicação das receitas de impostos e transferências na educação será identificada a partir da Fonte 001 - Recursos Ordinários, por exemplo.",
                            Exercicio = 2021,
                            Nome = "Receitas de Impostos e de Transferência de Impostos - Educação"
                        },
                        new
                        {
                            Id = 4,
                            CodigoPrincipal = "112",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com recursos recebidos do FUNDEB - Impostos, com base no art. 212-A, inciso I, da Constituição Federal. Esse código é de utilização alternativa à fonte 116.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB - Impostos 70%"
                        },
                        new
                        {
                            Id = 5,
                            CodigoPrincipal = "113",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com recursos recebidos do FUNDEB - Impostos, com base no art. 212-A, inciso I, da Constituição Federal. Esse código é de utilização alternativa à fonte 116.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB - Impostos 30%"
                        },
                        new
                        {
                            Id = 6,
                            CodigoPrincipal = "114",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com recursos de Complementação da União ao FUNDEB - VAAF, com base no art. 212-A, inciso V, \"a\" da Constituição Federal. Esse código é de utilização alternativa à fonte 117.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB 70% – Complementação da União - VAAF"
                        },
                        new
                        {
                            Id = 7,
                            CodigoPrincipal = "115",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com recursos de Complementação da União ao FUNDEB - VAAF, com base no art. 212-A, inciso V, \"a\" da Constituição Federal. Esse código é de utilização alternativa à fonte 117.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB 30% – Complementação da União - VAAF"
                        },
                        new
                        {
                            Id = 8,
                            CodigoPrincipal = "116",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com recursos recebidos do FUNDEB - Impostos, com base no art. 212-A, inciso I, da Constituição Federal. Esse código é de utilização alternativa às fontes 112 e 113.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB - Impostos - Entrada de Recursos"
                        },
                        new
                        {
                            Id = 9,
                            CodigoPrincipal = "116",
                            Detalhamento = "0060",
                            Especificacao = "Controle das despesas custeadas com recursos recebidos do FUNDEB - Impostos, com base no art. 212-A, inciso I, da Constituição Federal. Esse código é de utilização alternativa às fontes 112 e 113.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB - Impostos - Destinação 70%"
                        },
                        new
                        {
                            Id = 10,
                            CodigoPrincipal = "116",
                            Detalhamento = "0040",
                            Especificacao = "Controle das despesas custeadas com recursos recebidos do FUNDEB - Impostos, com base no art. 212-A, inciso I, da Constituição Federal. Esse código é de utilização alternativa às fontes 112 e 113.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB - Impostos - Destinação 30%"
                        },
                        new
                        {
                            Id = 11,
                            CodigoPrincipal = "117",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com recursos de Complementação da União ao FUNDEB - VAAF, com base no art. 212-A, inciso V, \"a\" da Constituição Federal. Esse código é de utilização alternativa às fontes 114 e 115.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB - Complementação da União - VAAF - Entrada de Recursos"
                        },
                        new
                        {
                            Id = 12,
                            CodigoPrincipal = "117",
                            Detalhamento = "0060",
                            Especificacao = "Controle das despesas custeadas com recursos de Complementação da União ao FUNDEB - VAAF, com base no art. 212-A, inciso V, \"a\" da Constituição Federal. Esse código é de utilização alternativa às fontes 114 e 115.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB – Complementação da União - VAAF - Destinação 70%"
                        },
                        new
                        {
                            Id = 13,
                            CodigoPrincipal = "117",
                            Detalhamento = "0040",
                            Especificacao = "Controle das despesas custeadas com recursos de Complementação da União ao FUNDEB - VAAF, com base no art. 212-A, inciso V, \"a\" da Constituição Federal. Esse código é de utilização alternativa às fontes 114 e 115.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB – Complementação da União - VAAF - Destinação 30%"
                        },
                        new
                        {
                            Id = 14,
                            CodigoPrincipal = "118",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências recebidas do Fundo Nacional do Desenvolvimento da Educação – FNDE, relativos aos repasses referentes ao salário-educação.Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 111 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB 70% – Complementação da União - VAAT"
                        },
                        new
                        {
                            Id = 15,
                            CodigoPrincipal = "119",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências do Fundo Nacional do Desenvolvimento da Educação – FNDE, destinados ao Programa Dinheiro Direto na Escola (PDDE).Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 111 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB 30% – Complementação da União - VAAT"
                        },
                        new
                        {
                            Id = 16,
                            CodigoPrincipal = "129",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências do Fundo Nacional do Desenvolvimento da Educação – FNDE, destinados ao Programa Nacional de Alimentação Escolar (PNAE).Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 111 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB - Complementação da União - VAAT - Entrada de Recursos "
                        },
                        new
                        {
                            Id = 17,
                            CodigoPrincipal = "129",
                            Detalhamento = "0060",
                            Especificacao = "Controle dos recursos originários de transferências do Fundo Nacional do Desenvolvimento da Educação – FNDE, destinados ao Programa Nacional de Apoio ao Transporte Escolar (PNATE).Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 111 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB – Complementação da União - VAAT - Destinação 70%"
                        },
                        new
                        {
                            Id = 18,
                            CodigoPrincipal = "129",
                            Detalhamento = "0040",
                            Especificacao = "Controle dos demais recursos originários de transferências do Fundo Nacional do Desenvolvimento da Educação – FNDE.Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 111 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB – Complementação da União - VAAT - Destinação 30%"
                        },
                        new
                        {
                            Id = 19,
                            CodigoPrincipal = "120",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências em virtude de assinatura de convênios, contratos de repasse ou legislações específicas, cuja destinação encontra-se vinculada a programas da educação.Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 111 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferência do Salário-Educação"
                        },
                        new
                        {
                            Id = 20,
                            CodigoPrincipal = "121",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de operações de crédito, cuja destinação encontra-se vinculada a programas da educação.Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 111 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferências de Recursos do FNDE Referentes ao Programa Dinheiro Direto na Escola (PDDE)"
                        },
                        new
                        {
                            Id = 21,
                            CodigoPrincipal = "122",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos vinculados à Educação, originários de transferências recebidas pelo Município, relativos  a Royalties e Participação Especial – Art. 2º da Lei nº 12.858/2013.Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 111 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferências de Recursos do FNDE Referentes ao Programa Nacional de Alimentação Escolar (PNAE)"
                        },
                        new
                        {
                            Id = 22,
                            CodigoPrincipal = "123",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 111 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferências de Recursos do FNDE Referentes ao Programa Nacional de Apoio ao Transporte Escolar (PNATE)"
                        },
                        new
                        {
                            Id = 23,
                            CodigoPrincipal = "124",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com os rendimentos dos recursos do FUNDEB quando houver necessidade. Essescódigos serão utilizados pelos entes da federação que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Outras Transferências de Recursos do FNDE"
                        },
                        new
                        {
                            Id = 24,
                            CodigoPrincipal = "125",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com os rendimentos dos recursos do FUNDEB quando houver necessidade. Essescódigos serão utilizados pelos entes da federação que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferências de Convênios ou de Contratos de Repasse vinculados à Educação"
                        },
                        new
                        {
                            Id = 25,
                            CodigoPrincipal = "130",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos demais recursos vinculados à Educação.",
                            Exercicio = 2021,
                            Nome = "Operações de Crédito Vinculadas à Educação"
                        },
                        new
                        {
                            Id = 26,
                            CodigoPrincipal = "140",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que vinculam os recursos de impostos à saúde no momento da arrecadação da receita. Nas situações em que os entes não efetuam a vinculação do recurso na origem, a aplicação das receitas de impostos e transferências na saúde será identificada a partir da Fonte 001 - Recursos Ordinários, por exemplo.",
                            Exercicio = 2021,
                            Nome = "Royalties do Petróleo Vinculados à Educação"
                        },
                        new
                        {
                            Id = 27,
                            CodigoPrincipal = "150",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências dos Fundos de saúde de outros municípios, referentes ao Sistema Único de Saúde (SUS).",
                            Exercicio = 2021,
                            Nome = "Receitas de Impostos e de Transferência de Impostos - Educação - Remuneração de Depósitos Bancários"
                        },
                        new
                        {
                            Id = 28,
                            CodigoPrincipal = "151",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências do Fundo Estadual de Saúde, referentes ao Sistema Único de Saúde (SUS).",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB - Remuneração de Depósitos Bancários"
                        },
                        new
                        {
                            Id = 29,
                            CodigoPrincipal = "152",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências do Fundo Nacional de Saúde, referentes ao Sistema Único de Saúde (SUS) e relacionados ao Bloco de Manutenção das Ações e Serviços Públicos de Saúde.",
                            Exercicio = 2021,
                            Nome = "Transferências do FUNDEB - Complementação da União - Remuneração de Depósitos Bancários"
                        },
                        new
                        {
                            Id = 30,
                            CodigoPrincipal = "190",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências do Fundo Nacional de Saúde, referentes ao Sistema Único de Saúde (SUS), relacionados ao Bloco de Manutneção das Ações e Serviços Públicos de Saúde, e destinados ao enfrentamento da COVID-19 no bojo da ação 21C0 do orçamento da União.",
                            Exercicio = 2021,
                            Nome = "Outros Recursos Vinculados à Educação"
                        },
                        new
                        {
                            Id = 31,
                            CodigoPrincipal = "211",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências do Fundo Nacional de Saúde, referentes ao Sistema Único de Saúde (SUS) e relacionados ao Bloco de Estruturação na Rede de Serviços Públicos de Saúde.",
                            Exercicio = 2021,
                            Nome = "Receitas de Impostos e de Transferência de Impostos - Saúde"
                        },
                        new
                        {
                            Id = 32,
                            CodigoPrincipal = "212",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências do Fundo Nacional de Saúde, referentes ao Sistema Único de Saúde (SUS), relacionados ao Bloco de Estruturação na Rede de Serviços Públicos de Saúde e destinados ao enfrentamento da COVID-19 no bojo da ação 21C0 do orçamento da União.",
                            Exercicio = 2021,
                            Nome = "Transferências Fundo a Fundo de Recursos do SUS provenientes dos Governos Municipais"
                        },
                        new
                        {
                            Id = 33,
                            CodigoPrincipal = "213",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências em virtude de assinatura de convênios, contratos de repasse ou legislações específicas, cuja destinação encontra-se vinculada a programas da saúde.",
                            Exercicio = 2021,
                            Nome = "Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Estadual"
                        },
                        new
                        {
                            Id = 34,
                            CodigoPrincipal = "214",
                            Detalhamento = "0000",
                            Especificacao = "Controlar dos recursos originários de operações de crédito, cuja destinação encontra-se vinculada a programas da saúde.",
                            Exercicio = 2021,
                            Nome = "Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Federal - Bloco de Manutenção das Ações e Serviços Públicos de Saúde"
                        },
                        new
                        {
                            Id = 35,
                            CodigoPrincipal = "214",
                            Detalhamento = "2100",
                            Especificacao = "Controle dos recursos vinculados à Saúde, originários de transferências recebidas pelo Município, relativos  a Royalties e Participação Especial – Art. 2º da Lei nº 12.858/2013.",
                            Exercicio = 2021,
                            Nome = "Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Federal - Bloco de Manutenção das Ações e Serviços Públicos de Saúde – Recursos destinados ao enfrentamento da COVID-19 no bojo da ação."
                        },
                        new
                        {
                            Id = 36,
                            CodigoPrincipal = "215",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 211 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Federal - Bloco de Estruturação da Rede de Serviços Públicos de Saúde."
                        },
                        new
                        {
                            Id = 37,
                            CodigoPrincipal = "215",
                            Detalhamento = "2100",
                            Especificacao = "Controle dos recursos originários de transferências do Fundo Nacional de Saúde, referentes ao Sistema Único de Saúde (SUS), relacionados ao Bloco de Estruturação na Rede de Serviços Públicos de Saúde e destinados ao enfrentamento da COVID-19 no bojo da ação 21C0 do orçamento da União.",
                            Exercicio = 2021,
                            Nome = "Transferências Fundo a Fundo de Recursos do SUS provenientes do Governo Federal - Bloco de Estruturação da Rede de Serviços Públicos de Saúde – Recursos destinados ao enfrentamento da COVID-19 no bojo da ação."
                        },
                        new
                        {
                            Id = 38,
                            CodigoPrincipal = "220",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências em virtude de assinatura de convênios, contratos de repasse ou legislações específicas, cuja destinação encontra-se vinculada a programas da saúde.",
                            Exercicio = 2021,
                            Nome = "Transferências de Convênios ou de Contratos de Repasse vinculados à Saúde"
                        },
                        new
                        {
                            Id = 39,
                            CodigoPrincipal = "230",
                            Detalhamento = "0000",
                            Especificacao = "Controlar dos recursos originários de operações de crédito, cuja destinação encontra-se vinculada a programas da saúde.",
                            Exercicio = 2021,
                            Nome = "Operações de Crédito vinculadas à Saúde"
                        },
                        new
                        {
                            Id = 40,
                            CodigoPrincipal = "240",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos vinculados à Saúde, originários de transferências recebidas pelo Município, relativos  a Royalties e Participação Especial – Art. 2º da Lei nº 12.858/2013.",
                            Exercicio = 2021,
                            Nome = "Royalties do Petróleo vinculados à Saúde"
                        },
                        new
                        {
                            Id = 41,
                            CodigoPrincipal = "250",
                            Detalhamento = "0000",
                            Especificacao = "Controle das despesas custeadas com os rendimentos do recursos de impostos e transferências de impostos consideradas para cumprimento do limite constitucional e será utilizado pelos entes da federação que utilizam a fonte de recuros 211 e que, em razão da forma de verificação do cumprimento do limite mínimo, necessitam identificar esses recursos por meio de uma fonte específica.",
                            Exercicio = 2021,
                            Nome = "Receita de Impostos e de Transferência de Impostos - Saúde - Remuneração de Depósitos Bancários"
                        },
                        new
                        {
                            Id = 42,
                            CodigoPrincipal = "290",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos não enquadrados em especificações próprias, cuja destinação encontra-se vinculada a programas da saúde.",
                            Exercicio = 2021,
                            Nome = "Outros Recursos Vinculados à Saúde"
                        },
                        new
                        {
                            Id = 43,
                            CodigoPrincipal = "311",
                            Detalhamento = "0000",
                            Especificacao = "Controle os recursos originários de transferências do Fundo Nacional de Assistência Social - Lei Federal nº 8.742, 07/12/1993.",
                            Exercicio = 2021,
                            Nome = "Transferência de Recursos do Fundo Nacional de Assistência Social - FNAS"
                        },
                        new
                        {
                            Id = 44,
                            CodigoPrincipal = "312",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de transferências em virtude de assinatura de convênios ou legislações específicas, cuja destinação encontra-se vinculada a programas da assistência social.",
                            Exercicio = 2021,
                            Nome = "Transferências de Convênios - Assistência Social"
                        },
                        new
                        {
                            Id = 45,
                            CodigoPrincipal = "390",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos não enquadrados em especificações próprias, cuja destinação encontra-se vinculada a programas da assistência social.",
                            Exercicio = 2021,
                            Nome = "Outros Recursos Vinculados à Assistência Social"
                        },
                        new
                        {
                            Id = 46,
                            CodigoPrincipal = "410",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos vinculados ao fundo em capitalização do RPPS. Esse plano existe tanto nos entes que segregaram quanto no",
                            Exercicio = 2021,
                            Nome = "Recursos vinculados ao RPPS - Fundo em Capitalização (Plano Previdenciário)"
                        },
                        new
                        {
                            Id = 47,
                            CodigoPrincipal = "420",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos vinculados ao fundo em repartiçãoo do RPPS. Esse plano existe somente nos entes que segregaram a massa d",
                            Exercicio = 2021,
                            Nome = "Recursos vinculados ao RPPS - Fundo em Repartição (Plano Financeiro)"
                        },
                        new
                        {
                            Id = 48,
                            CodigoPrincipal = "430",
                            Detalhamento = "0000",
                            Especificacao = "Constrole dos recursos destinados ao custeio das despesas necessárias à organização e ao funcionamento da unidade gestora do R",
                            Exercicio = 2021,
                            Nome = "Recursos vinculados ao RPPS - Taxa de Administração"
                        },
                        new
                        {
                            Id = 49,
                            CodigoPrincipal = "450",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos vinculados ao RGPS (uso exclusivo da União).",
                            Exercicio = 2021,
                            Nome = "Recursos vinculados ao RGPS"
                        },
                        new
                        {
                            Id = 50,
                            CodigoPrincipal = "460",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos vinculados aos benefícios previdenciários concedidos aos militares e pensionistas militares.",
                            Exercicio = 2021,
                            Nome = "Recursos vinculados às pensões e aos inativos militares"
                        },
                        new
                        {
                            Id = 51,
                            CodigoPrincipal = "510",
                            Detalhamento = "0000",
                            Especificacao = "Recursos originários de transferências federais em virtude de assinatura de convênios, contratos de repasse ou legislações específicas, cuja destinação encontra-se vinculada aos seus objetos. Não serão controlados por esta fonte os recursos de convênios vinculados a programas da educação, da saúde e da assistência social, cujo controle será realizado através das fontes 125, 220 e 312, respectivamente. ",
                            Exercicio = 2021,
                            Nome = "Outras Transferências de Convênios ou Contratos de Repasse da União"
                        },
                        new
                        {
                            Id = 52,
                            CodigoPrincipal = "520",
                            Detalhamento = "0000",
                            Especificacao = "Recursos originários de transferências estaduais em virtude de assinatura de convênios, contratos de repasse ou legislações específicas, cuja destinação encontra-se vinculada aos seus objetos. Não serão controlados por esta fonte os recursos de convênios ou contratos de repasse vinculados a programas da educação, da saúde e da assistência social, cujo controle será realizado através das fontes 125, 220 e 312, respectivamente. ",
                            Exercicio = 2021,
                            Nome = "Outras Transferências de Convênios ou Contratos de Repasse dos Estados"
                        },
                        new
                        {
                            Id = 53,
                            CodigoPrincipal = "530",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários da arrecadação da cota-parte royalties.",
                            Exercicio = 2021,
                            Nome = "Transferência da União Referente a Royalties do Petróleo"
                        },
                        new
                        {
                            Id = 54,
                            CodigoPrincipal = "540",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários das transferências de royalties pelos Estados.",
                            Exercicio = 2021,
                            Nome = "Transferência dos Estados Referente a Royalties do Petróleo"
                        },
                        new
                        {
                            Id = 55,
                            CodigoPrincipal = "550",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos provenientes de emendas individuais impositivas ao orçamento da União nos termos do art. 166-A, inciso I, da Constitui",
                            Exercicio = 2021,
                            Nome = "Transferência Especial da União"
                        },
                        new
                        {
                            Id = 56,
                            CodigoPrincipal = "560",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos provenientes de transferência da União com base no disposto no inciso I do art. 5º da lei complementar 173/2020.",
                            Exercicio = 2021,
                            Nome = "Transferências da União – inciso I do art. 5º da Lei Complementar 173/2020 "
                        },
                        new
                        {
                            Id = 57,
                            CodigoPrincipal = "610",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos da CIDE.",
                            Exercicio = 2021,
                            Nome = "Contribuição de Intervenção no Domínio Econômico - CIDE"
                        },
                        new
                        {
                            Id = 58,
                            CodigoPrincipal = "620",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos da COSIP, nos termos do artigo 149-A da Constituição Federal da República.",
                            Exercicio = 2021,
                            Nome = "Contribuição para o Custeio do Serviço de Iluminação Pública - COSIP"
                        },
                        new
                        {
                            Id = 59,
                            CodigoPrincipal = "630",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos com a cobrança das multas de trânsito nos termos do artigo nº. 320 da Lei nº 9.503/1997 - Código de Trânsito Brasileiro.",
                            Exercicio = 2021,
                            Nome = "Recursos Vinculados ao Trânsito"
                        },
                        new
                        {
                            Id = 60,
                            CodigoPrincipal = "910",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos próprios dos Consórcios Públicos",
                            Exercicio = 2021,
                            Nome = "Recursos próprios dos consórcios"
                        },
                        new
                        {
                            Id = 61,
                            CodigoPrincipal = "920",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos originários de operações de crédito, exceto as operações cuja aplicação estejam destinadas a programas de educação e saúde.",
                            Exercicio = 2021,
                            Nome = "Recursos de Operações de Crédito"
                        },
                        new
                        {
                            Id = 62,
                            CodigoPrincipal = "930",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos advindos da alienação de bens nos termos do art. 44 da LRF.",
                            Exercicio = 2021,
                            Nome = "Recursos de Alienação de Bens/Ativos"
                        },
                        new
                        {
                            Id = 63,
                            CodigoPrincipal = "940",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos de outras transferências vinculadas.",
                            Exercicio = 2021,
                            Nome = "Outras vinculações de transferências"
                        },
                        new
                        {
                            Id = 64,
                            CodigoPrincipal = "950",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos de outras taxas e contribuições vinculadas",
                            Exercicio = 2021,
                            Nome = "Outras vinculações de taxas e contribuições"
                        },
                        new
                        {
                            Id = 65,
                            CodigoPrincipal = "961",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos de depósitos judiciais apropriados pelo ente de lides das quais o ente faz parte.",
                            Exercicio = 2021,
                            Nome = "Recursos de depósitos judiciais – Lides das quais o ente faz parte"
                        },
                        new
                        {
                            Id = 66,
                            CodigoPrincipal = "962",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos de depósitos judiciais apropriados pelo ente de lides das quais o ente não faz parte.",
                            Exercicio = 2021,
                            Nome = "Recursos de depósitos judiciais – Lides das quais o ente não faz parte"
                        },
                        new
                        {
                            Id = 67,
                            CodigoPrincipal = "971",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos financeiros junto aos tribunais de justiça vinculados ",
                            Exercicio = 2021,
                            Nome = "Recursos extraorçamentários vinculados a precatórios"
                        },
                        new
                        {
                            Id = 68,
                            CodigoPrincipal = "972",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos financeiros junto aos tribunais de justiça vinculados ",
                            Exercicio = 2021,
                            Nome = "Recursos extraorçamentários vinculados a depósitos judiciais"
                        },
                        new
                        {
                            Id = 69,
                            CodigoPrincipal = "979",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos financeiros que não transitam pelo orçamento, como dep",
                            Exercicio = 2021,
                            Nome = "Outros recursos extraorçamentários"
                        },
                        new
                        {
                            Id = 70,
                            CodigoPrincipal = "980",
                            Detalhamento = "0000",
                            Especificacao = "Classificação temporária enquanto não se identifica a correta vinculação.",
                            Exercicio = 2021,
                            Nome = "Recursos não classificados – a classificar"
                        },
                        new
                        {
                            Id = 71,
                            CodigoPrincipal = "990",
                            Detalhamento = "0000",
                            Especificacao = "Controle dos recursos cuja aplicação seja vinculada e não tenha sido enquadrado em outras especificações.",
                            Exercicio = 2021,
                            Nome = "Outros Recursos Vinculados"
                        });
                });

            modelBuilder.Entity("OpenSiconfi.Domain.Entities.InformacaoComplementar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CodigoIC")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("codigo_ic");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Digito")
                        .HasColumnType("integer")
                        .HasColumnName("digito");

                    b.Property<int>("Exercicio")
                        .HasColumnType("integer")
                        .HasColumnName("exercicio");

                    b.Property<string>("Finalidade")
                        .HasColumnType("text")
                        .HasColumnName("finalidade");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("informacao_complementar");
                });

            modelBuilder.Entity("OpenSiconfi.Domain.Entities.NaturezaReceita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("C")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("c");

                    b.Property<string>("D1")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("d1");

                    b.Property<string>("D3")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("d3");

                    b.Property<string>("DD2")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("dd2");

                    b.Property<string>("Descriciao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detalhamento");

                    b.Property<string>("E")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("E");

                    b.Property<int>("Exercicio")
                        .HasColumnType("integer")
                        .HasColumnName("exercicio");

                    b.Property<string>("NR")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("nr");

                    b.Property<string>("NormaCorrespondente")
                        .HasColumnType("text")
                        .HasColumnName("norma_correspondente");

                    b.Property<string>("O")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("o");

                    b.Property<string>("T")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("t");

                    b.Property<string>("Valorizavel")
                        .HasColumnType("text")
                        .HasColumnName("valorizavel");

                    b.HasKey("Id");

                    b.ToTable("natureza_receita");
                });
#pragma warning restore 612, 618
        }
    }
}
